#!/bin/bash
#
# Xcode Cloud post-clone script
# Generates SideBar.local.xcconfig from environment variables
#
# Required environment variables (set in Xcode Cloud):
#   - API_BASE_URL
#   - SUPABASE_URL
#   - SUPABASE_ANON_KEY
#   - APP_GROUP_ID
#   - KEYCHAIN_ACCESS_GROUP
#   - KEYCHAIN_SERVICE

set -euo pipefail

echo "=== ci_post_clone.sh: Installing SwiftLint ==="
brew install swiftlint

echo "=== ci_post_clone.sh: Generating SideBar.local.xcconfig ==="

# Validate required environment variables
required_vars=("API_BASE_URL" "SUPABASE_URL" "SUPABASE_ANON_KEY" "APP_GROUP_ID" "KEYCHAIN_ACCESS_GROUP" "KEYCHAIN_SERVICE")
for var in "${required_vars[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        echo "Error: Required environment variable $var is not set"
        exit 1
    fi
done

# Escape forward slashes for xcconfig format (// is treated as comment)
escape_url() {
    echo "$1" | sed 's/\//\\\//g'
}

API_BASE_URL_ESCAPED=$(escape_url "$API_BASE_URL")
SUPABASE_URL_ESCAPED=$(escape_url "$SUPABASE_URL")
R2_ENDPOINT_ESCAPED=$(escape_url "${R2_ENDPOINT:-}")
R2_BUCKET_ESCAPED=$(escape_url "${R2_BUCKET:-}")
R2_FAVICON_BUCKET_ESCAPED=$(escape_url "${R2_FAVICON_BUCKET:-}")

# Generate the xcconfig content
XCCONFIG_CONTENT="// Auto-generated by ci_post_clone.sh for Xcode Cloud builds
// DO NOT COMMIT THIS FILE

API_BASE_URL = ${API_BASE_URL_ESCAPED}

SUPABASE_URL = ${SUPABASE_URL_ESCAPED}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
R2_ENDPOINT = ${R2_ENDPOINT_ESCAPED}
R2_BUCKET = ${R2_BUCKET_ESCAPED}
R2_FAVICON_BUCKET = ${R2_FAVICON_BUCKET_ESCAPED}

APP_GROUP_ID = ${APP_GROUP_ID}
KEYCHAIN_ACCESS_GROUP = ${KEYCHAIN_ACCESS_GROUP}
KEYCHAIN_SERVICE = ${KEYCHAIN_SERVICE}

INFOPLIST_KEY_API_BASE_URL = \$(API_BASE_URL)
INFOPLIST_KEY_SUPABASE_URL = \$(SUPABASE_URL)
INFOPLIST_KEY_SUPABASE_ANON_KEY = \$(SUPABASE_ANON_KEY)
INFOPLIST_KEY_R2_ENDPOINT = \$(R2_ENDPOINT)
INFOPLIST_KEY_R2_BUCKET = \$(R2_BUCKET)
INFOPLIST_KEY_R2_FAVICON_BUCKET = \$(R2_FAVICON_BUCKET)
INFOPLIST_KEY_APP_GROUP_ID = \$(APP_GROUP_ID)
INFOPLIST_KEY_KEYCHAIN_ACCESS_GROUP = \$(KEYCHAIN_ACCESS_GROUP)
INFOPLIST_KEY_KEYCHAIN_SERVICE = \$(KEYCHAIN_SERVICE)"

# Write to both locations the project might reference
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
SIDEBAR_DIR="$REPO_ROOT/ios/sideBar"

echo "$XCCONFIG_CONTENT" > "$SIDEBAR_DIR/SideBar.local.xcconfig"
echo "Created: $SIDEBAR_DIR/SideBar.local.xcconfig"

echo "$XCCONFIG_CONTENT" > "$SIDEBAR_DIR/Config/SideBar.local.xcconfig"
echo "Created: $SIDEBAR_DIR/Config/SideBar.local.xcconfig"

echo "=== ci_post_clone.sh: Done ==="
