included:
  - sideBar
  - sideBarTests
  - ShareExtension

excluded:
  - sideBar.xcodeproj
  - .build
  - .swiftpm
  - Carthage
  - Pods
  - Config

disabled_rules:
  - cyclomatic_complexity
  - duplicate_imports
  - file_length
  - function_body_length
  - function_parameter_count
  - implicit_optional_initialization
  - large_tuple
  - multiple_closures_with_trailing_closure
  - nesting
  - non_optional_string_data_conversion
  - optional_data_string_conversion
  - for_where
  - redundant_string_enum_value
  - syntactic_sugar
  - todo
  - trailing_comma
  - type_body_length
  - unused_closure_parameter
  - vertical_whitespace

line_length:
  warning: 140
  error: 200

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
